/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  BarChart3,
  Bell,
  Bot,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  Command,
  MoreHorizontal,
  Search,
  Send,
  ShieldCheck,
  TrendingUp,
  User,
  UserCheck,
  Users,
} from "lucide-react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { adminApi, aiDataApi } from "@/lib/api";
import { asArray, formatCurrency, timeAgo } from "@/lib/utils";
import { useViewportPageSize } from "@/hooks/use-viewport-page-size";

const panelClass =
  "rounded-[8px] border border-[#14304c] bg-[#06162a]/95 shadow-[0_0_0_1px_rgba(22,54,86,0.24),0_18px_55px_rgba(0,0,0,0.22)]";

const iconTone: Record<string, string> = {
  blue: "bg-[#0b3b79]/70 text-[#2d8cff] ring-[#1268d4]/30",
  green: "bg-[#063f32]/75 text-[#18d589] ring-[#0bbf72]/30",
  purple: "bg-[#35206c]/75 text-[#a065ff] ring-[#7145d9]/30",
  amber: "bg-[#4a2f07]/75 text-[#ff9f0a] ring-[#d98400]/30",
};

const fallbackTrend = [
  { name: "May 1", total: 24000 },
  { name: "May 3", total: 38000 },
  { name: "May 5", total: 35000 },
  { name: "May 7", total: 42000 },
  { name: "May 9", total: 39000 },
  { name: "May 11", total: 56000 },
  { name: "May 13", total: 74000 },
  { name: "May 15", total: 69000 },
  { name: "May 17", total: 52000 },
  { name: "May 19", total: 48000 },
  { name: "May 21", total: 62000 },
  { name: "May 23", total: 76000 },
  { name: "May 25", total: 73000 },
  { name: "May 27", total: 84000 },
  { name: "May 29", total: 90000 },
];

const fallbackPartners = [
  { _id: "1", userId: { name: "Max Mustermann" }, totalCustomers: 128, totalEarnings: 24580, conversionRate: 28.4 },
  { _id: "2", userId: { name: "Anna Schneider" }, totalCustomers: 96, totalEarnings: 18240, conversionRate: 25.7 },
  { _id: "3", userId: { name: "Thomas Weber" }, totalCustomers: 74, totalEarnings: 13870, conversionRate: 23.1 },
  { _id: "4", userId: { name: "Laura Hoffmann" }, totalCustomers: 62, totalEarnings: 11230, conversionRate: 21.6 },
  { _id: "5", userId: { name: "Michael Braun" }, totalCustomers: 41, totalEarnings: 7340, conversionRate: 18.9 },
];

const fallbackActivity = [
  { _id: "a1", description: 'New customer "Barber Shop Zurich"', user_id: { name: "Created by Max Mustermann" }, createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(), tone: "blue" },
  { _id: "a2", description: "New lead generated in Berlin", user_id: { name: "Generated by Anna Schneider" }, createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(), tone: "amber" },
  { _id: "a3", description: 'Deal closed "Tattoo Studio Hamburg"', user_id: { name: "Closed by Thomas Weber" }, createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(), tone: "green" },
  { _id: "a4", description: 'Partner "Felix Bauer" registered', user_id: { name: "New partner registration" }, createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), tone: "purple" },
  { _id: "a5", description: 'Customer "Barber Lounge Munich"', user_id: { name: "Upgraded to Pro Plan" }, createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), tone: "blue" },
];

function compactNumber(value: number) {
  return new Intl.NumberFormat("en-US").format(value);
}

function pctOf(value: number, total: number) {
  if (!total) return "0%";
  return `${Math.round((value / total) * 1000) / 10}%`;
}

function MiniSelect() {
  return (
    <button className="h-8 rounded-[6px] border border-[#183657] bg-[#061224] px-3 text-[11px] font-medium text-[#c6d3e6]">
      This Month
    </button>
  );
}

function PanelTitle({ title, action = true }: { title: string; action?: boolean }) {
  return (
    <div className="flex h-12 items-center justify-between px-5">
      <h2 className="text-[15px] font-semibold text-[#f1f6ff]">{title}</h2>
      {action ? <MiniSelect /> : <button className="text-[12px] font-medium text-[#43a1ff]">View all</button>}
    </div>
  );
}

function MetricCard({ title, value, delta, icon: Icon, tone }: any) {
  return (
    <div className={`${panelClass} min-h-0 p-[clamp(0.75rem,1.3vw,1.25rem)]`}>
      <div className={`flex h-11 w-11 items-center justify-center rounded-full ring-1 ${iconTone[tone]}`}>
        <Icon className="h-5 w-5" />
      </div>
      <p className="mt-5 text-[13px] font-semibold text-[#cbd7e8]">{title}</p>
      <p className="dashboard-fluid-value mt-2 font-semibold text-white">{value}</p>
      <p className="mt-3 text-[13px] font-semibold text-[#16d486]">up {delta}</p>
      <p className="mt-1 text-[12px] text-[#8b99ad]">vs last month</p>
    </div>
  );
}

function AvatarDot({ index }: { index: number }) {
  const colors = ["#e8d5c5", "#d98769", "#d7e7f7", "#f3d6bd", "#e1cab2"];
  return (
    <div
      className="flex h-8 w-8 items-center justify-center rounded-full border border-white/20 text-[11px] font-bold text-[#122032]"
      style={{ background: colors[index % colors.length] }}
    >
      {["M", "A", "T", "L", "B"][index % 5]}
    </div>
  );
}

export function AdminDashboardReference() {
  const queryClient = useQueryClient();
  const [chatInput, setChatInput] = useState("");
  const [chatReply, setChatReply] = useState<string | null>(null);
  const partnerPageSize = useViewportPageSize({
    rowHeight: 50,
    reservedHeight: 500,
    min: 3,
    max: 5,
  });
  const activityPageSize = useViewportPageSize({
    rowHeight: 50,
    reservedHeight: 500,
    min: 3,
    max: 5,
  });

  const { data: dashboardResponse } = useQuery({
    queryKey: ["admin-dashboard"],
    queryFn: () => adminApi.getDashboardStats().then((response) => response.data),
  });

  const { data: historyResponse } = useQuery({
    queryKey: ["ai-data-history"],
    queryFn: () => aiDataApi.getAll().then((response) => response.data),
  });

  const sendMutation = useMutation({
    mutationFn: (msg: string) => aiDataApi.create({ message: msg }),
    onSuccess: (res) => {
      setChatReply(res.data?.data?.aireplay || "Here are the partners with the lowest conversion rates this month.");
      queryClient.invalidateQueries({ queryKey: ["ai-data-history"] });
    },
    onError: () => setChatReply("I could not reach the assistant service just now."),
  });

  const dashboard = dashboardResponse?.data || {};
  const conversations = asArray<any>(historyResponse);
  const lastConversation = conversations[0];

  const revenueTrend = useMemo(() => {
    const mapped = asArray<any>(dashboard.revenueTrend).map((point, index) => ({
      name: point.label
        ? new Date(point.label).toLocaleDateString("en-US", { month: "short", day: "numeric" })
        : `May ${index + 1}`,
      total: point.total || 0,
    }));
    return mapped.length >= 3 ? mapped : fallbackTrend;
  }, [dashboard.revenueTrend]);

  const topPartners = (dashboard.topPartners || []).length ? dashboard.topPartners : fallbackPartners;
  const recentActivity = (dashboard.recentActivity || []).length ? dashboard.recentActivity : fallbackActivity;
  const totalCustomers = dashboard.totalCustomers || 1248;
  const activeCustomers = dashboard.activeCustomers || 983;
  const totalRevenue = dashboard.totalRevenue || 482245;
  const monthlyRevenue = dashboard.monthlyRevenue || 78245;
  const totalLeads = dashboard.totalLeads || 3284;
  const conversionRate = dashboard.conversionRate || 24.6;
  const funnel = dashboard.leadsFunnel || {};
  const funnelTotal = Number(funnel.total ?? totalLeads ?? 0);
  const funnelContacted = Number(funnel.contacted ?? 0);
  const funnelInterested = Number(funnel.interested ?? 0);
  const funnelClosed = Number(funnel.closed ?? 0);

  const stats = [
    { title: "Total Customers", value: compactNumber(totalCustomers), delta: "12.5%", icon: User, tone: "blue" },
    { title: "Active Customers", value: compactNumber(activeCustomers), delta: "8.7%", icon: UserCheck, tone: "green" },
    { title: "Total Revenue", value: formatCurrency(totalRevenue, "$"), delta: "15.2%", icon: CircleDollarSign, tone: "purple" },
    { title: "Monthly Revenue", value: formatCurrency(monthlyRevenue, "$"), delta: "10.3%", icon: CircleDollarSign, tone: "blue" },
    { title: "Total Leads", value: compactNumber(totalLeads), delta: "18.7%", icon: CircleDollarSign, tone: "amber" },
    { title: "Conversion Rate", value: `${conversionRate}%`, delta: "4.1%", icon: TrendingUp, tone: "blue" },
  ];

  const insightItems = [
    { title: "3 underperforming partners", desc: "View performance report", icon: BarChart3, tone: "blue" },
    { title: "Leads not contacted", desc: `${compactNumber(Math.max(0, funnelTotal - funnelContacted))} leads need attention`, icon: CircleDollarSign, tone: "purple" },
    { title: "Revenue insight", desc: "10% higher than last month", icon: CircleDollarSign, tone: "amber" },
    { title: "System health", desc: "All systems operational", icon: ShieldCheck, tone: "green" },
  ];

  function handleSend() {
    const message = chatInput.trim();
    if (!message || sendMutation.isPending) return;
    sendMutation.mutate(message);
    setChatInput("");
  }

  return (
    <div className="dashboard-page bg-[#020a14] px-[clamp(0.75rem,1.5vw,1.25rem)] py-[clamp(0.75rem,1.5vw,1.25rem)] text-[#dce7f7]">
      <div className="mb-[clamp(0.75rem,1.4vw,1.5rem)] flex items-start justify-between gap-6">
        <div>
          <h1 className="text-[28px] font-semibold leading-tight tracking-[-0.01em] text-white">Dashboard</h1>
          <p className="mt-2 text-[14px] text-[#c5cfdd]">Welcome back, Admin. Here&apos;s what&apos;s happening in your system.</p>
        </div>
        <div className="flex items-center gap-5">
          <div className="relative hidden h-10 w-[304px] items-center rounded-[8px] border border-[#1a395a] bg-[#071427] px-3 xl:flex">
            <Search className="h-5 w-5 text-[#93a4ba]" />
            <input className="min-w-0 flex-1 bg-transparent px-3 text-[13px] outline-none placeholder:text-[#9aa7b8]" placeholder="Search anything..." />
            <kbd className="flex h-6 items-center gap-1 rounded-[5px] bg-[#15243a] px-2 text-[11px] text-[#c5d0df]">
              <Command className="h-3 w-3" /> K
            </kbd>
          </div>
          <button className="relative flex h-10 w-10 items-center justify-center rounded-full border border-[#1a395a] text-[#d8e4f3]">
            <Bell className="h-5 w-5" />
            <span className="absolute -right-0.5 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-[#155dff] text-[10px] font-bold text-white">3</span>
          </button>
          <div className="flex items-center gap-3">
            <AvatarDot index={0} />
            <div>
              <p className="text-[14px] font-semibold text-white">Admin User</p>
              <p className="text-[12px] font-medium text-[#1db3ff]">System Administrator</p>
            </div>
            <ChevronRight className="h-4 w-4 rotate-90 text-[#a9b6c8]" />
          </div>
        </div>
      </div>

      <div className="dashboard-kpi-grid">
        {stats.map((stat) => <MetricCard key={stat.title} {...stat} />)}
      </div>

      <div className="mt-4 grid min-h-0 grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1fr)_355px]">
        <div className="min-h-0 space-y-4">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1.45fr)_minmax(330px,0.85fr)]">
            <section className={`${panelClass} min-h-0`}>
              <PanelTitle title="Revenue Overview" />
              <div className="grid dashboard-chart grid-cols-[minmax(120px,160px)_minmax(0,1fr)] px-5 pb-5">
                <div className="flex flex-col justify-center">
                  <p className="text-[27px] font-semibold text-white">{formatCurrency(monthlyRevenue, "$")}</p>
                  <p className="mt-2 text-[14px] font-medium text-[#c2ccda]">Total Revenue</p>
                  <p className="mt-5 text-[13px] text-[#16d486]">up 10.3% <span className="text-[#8897aa]">vs last month</span></p>
                </div>
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={revenueTrend} margin={{ top: 12, right: 8, left: 0, bottom: 2 }}>
                    <defs>
                      <linearGradient id="revenueFillAdmin" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#1062ff" stopOpacity={0.52} />
                        <stop offset="100%" stopColor="#08264c" stopOpacity={0.08} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid stroke="#19324e" vertical={false} />
                    <XAxis dataKey="name" axisLine={false} tickLine={false} interval={2} tick={{ fill: "#8997aa", fontSize: 11 }} />
                    <YAxis axisLine={false} tickLine={false} tickFormatter={(v) => `$${Math.round(Number(v) / 1000)}K`} tick={{ fill: "#8997aa", fontSize: 11 }} width={48} />
                    <Tooltip
                      contentStyle={{ background: "#071427", border: "1px solid #173553", borderRadius: 8, color: "#eaf2ff" }}
                      formatter={(value) => [formatCurrency(Number(value), "$"), "Revenue"]}
                    />
                    <Area type="monotone" dataKey="total" stroke="#267dff" strokeWidth={3} fill="url(#revenueFillAdmin)" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </section>

            <section className={`${panelClass} min-h-0 overflow-hidden`}>
              <PanelTitle title="Leads Funnel" />
              <div className="grid h-[clamp(12rem,24dvh,15.5rem)] min-h-0 grid-cols-[minmax(0,1fr)_minmax(5.5rem,7rem)] gap-3 px-5 pb-5">
                <div className="flex min-h-0 flex-col items-center justify-center gap-2">
                  {[100, 82, 58, 38].map((width, index) => (
                    <div
                      key={width}
                      className="min-h-0 flex-1 bg-gradient-to-b from-[#1558c9] to-[#0b326e]"
                      style={{
                        width: `${width}%`,
                        clipPath: "polygon(0 0, 100% 0, 86% 100%, 14% 100%)",
                        opacity: 1 - index * 0.12,
                      }}
                    />
                  ))}
                </div>
                <div className="flex min-h-0 flex-col justify-center gap-[clamp(0.55rem,1.6dvh,1rem)]">
                  {[
                    ["Leads", funnelTotal, "100%"],
                    ["Contacted", funnelContacted, pctOf(funnelContacted, funnelTotal)],
                    ["Interested", funnelInterested, pctOf(funnelInterested, funnelTotal)],
                    ["Closed", funnelClosed, pctOf(funnelClosed, funnelTotal)],
                  ].map(([label, value, pct]) => (
                    <div key={label as string}>
                      <p className="text-[clamp(0.95rem,1.6vw,1.3rem)] font-semibold leading-none text-white">{compactNumber(Number(value))}</p>
                      <p className="mt-1 text-[12px] text-[#b7c2d1]">{label}</p>
                      <p className="text-[12px] text-[#77869a]">{pct}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          </div>

          <div className="grid grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1.15fr)_minmax(360px,0.85fr)]">
            <section className={`${panelClass} min-h-0`}>
              <PanelTitle title="Top Performing Partners" action={false} />
              <div className="px-5 pb-4">
                <div className="grid grid-cols-[42px_minmax(150px,1fr)_96px_112px_132px] border-b border-[#16304d] pb-3 text-[11px] text-[#8796ab]">
                  <span />
                  <span>Partner</span>
                  <span>Customers</span>
                  <span>Revenue</span>
                  <span>Conversion Rate</span>
                </div>
                <div>
                  {topPartners.slice(0, partnerPageSize).map((partner: any, index: number) => {
                    const conversion = Number(partner.conversionRate ?? Math.min(28.4, 18.9 + (4 - index) * 2.2));
                    return (
                      <div key={partner._id || index} className="grid h-[50px] grid-cols-[42px_minmax(150px,1fr)_96px_112px_132px] items-center border-b border-[#102944] text-[12px] last:border-0">
                        <span className="text-[#9aa8ba]">{index + 1}</span>
                        <div className="flex items-center gap-3">
                          <AvatarDot index={index} />
                          <span className="truncate font-medium text-[#e8eef8]">{partner.userId?.name || partner.businessName || "Partner"}</span>
                        </div>
                        <span className="text-[#d9e3ef]">{partner.totalCustomers ?? partner.customerCount ?? 0}</span>
                        <span className="font-semibold text-[#e8eef8]">{formatCurrency(partner.totalEarnings || 0, "$")}</span>
                        <div>
                          <span className="text-[#e8eef8]">{conversion.toFixed(1)}%</span>
                          <div className="mt-1 h-[4px] w-[104px] overflow-hidden rounded-full bg-[#112842]">
                            <div className="h-full rounded-full bg-[#24d98b]" style={{ width: `${Math.min(100, conversion * 3.2)}%` }} />
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </section>

            <section className={`${panelClass} min-h-0`}>
              <PanelTitle title="Recent Activity" action={false} />
              <div className="space-y-0 px-5 pb-4">
                {recentActivity.slice(0, activityPageSize).map((item: any, index: number) => {
                  const ToneIcon = [User, CircleDollarSign, CheckCircle2, Users, TrendingUp][index % 5];
                  const tone = item.tone || ["blue", "amber", "green", "purple", "blue"][index % 5];
                  return (
                    <div key={item._id || index} className="flex h-[50px] items-center gap-3 border-b border-[#102944] last:border-0">
                      <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ring-1 ${iconTone[tone]}`}>
                        <ToneIcon className="h-4 w-4" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-[12px] font-semibold text-[#edf4ff]">{item.description || item.action || "Activity logged"}</p>
                        <p className="truncate text-[11px] text-[#8796aa]">{item.user_id?.name || "System"}</p>
                      </div>
                      <span className="shrink-0 text-[11px] text-[#8a99ac]">{timeAgo(item.timestamp || item.createdAt)}</span>
                    </div>
                  );
                })}
              </div>
            </section>
          </div>
        </div>

        <aside className="space-y-4">
          <section className={`${panelClass} min-h-0 p-4`}>
            <div className="mb-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="h-2.5 w-2.5 rounded-full bg-[#18d589] shadow-[0_0_12px_rgba(24,213,137,0.8)]" />
                <h2 className="text-[14px] font-semibold text-white">Kora Assistant</h2>
                <span className="h-2 w-2 rounded-full bg-[#18d589]" />
                <span className="text-[12px] font-medium text-[#17d985]">Online</span>
              </div>
              <MoreHorizontal className="h-5 w-5 text-[#a0aec0]" />
            </div>
            <div className="flex items-center justify-center gap-7 py-2">
              <div className="relative h-[78px] w-[78px]">
                <Image src="/kora.png" alt="Kora assistant" fill sizes="78px" className="object-contain drop-shadow-[0_0_18px_rgba(0,184,255,0.85)]" priority />
              </div>
              <div>
                <p className="text-[14px] font-semibold text-[#f1f6ff]">Hi Admin!</p>
                <p className="mt-2 text-[13px] text-[#b6c3d5]">Here&apos;s what I found for you today.</p>
              </div>
            </div>
            <div className="mt-4 space-y-2">
              {insightItems.map((item) => {
                const Icon = item.icon;
                return (
                  <button key={item.title} className="flex h-[57px] w-full items-center gap-3 rounded-[8px] border border-[#16314f] bg-[#0b1c32] px-3 text-left hover:bg-[#0f263f]">
                    <span className={`flex h-8 w-8 items-center justify-center rounded-[7px] ring-1 ${iconTone[item.tone]}`}>
                      <Icon className="h-4 w-4" />
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-[12px] font-semibold text-[#eef5ff]">{item.title}</span>
                      <span className="block truncate text-[11px] text-[#8a99ac]">{item.desc}</span>
                    </span>
                    <ChevronRight className="h-4 w-4 text-[#a5b3c4]" />
                  </button>
                );
              })}
            </div>
            <div className="mt-4 flex justify-end">
              <div className="max-w-[230px] rounded-[8px] bg-[#0648c8] px-4 py-3 text-[12px] leading-5 text-white">
                Show me partners with low conversion rate.
                <div className="mt-1 text-right text-[10px] text-[#bdd4ff]">10:45 AM</div>
              </div>
            </div>
            <div className="mt-3 flex items-start gap-3">
              <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-[#00b7ff] text-[#00c2ff]">
                <Bot className="h-4 w-4" />
              </div>
              <div className="rounded-[8px] bg-[#0b1c32] px-4 py-3 text-[12px] leading-5 text-[#d9e4f3]">
                {chatReply || lastConversation?.aireplay || "Here are the partners with the lowest conversion rates this month."}
                <button className="mt-2 block rounded-[5px] border border-[#164d8f] px-3 py-1 text-[12px] font-semibold text-[#4aa4ff]">View Report</button>
              </div>
            </div>
            <div className="relative mt-4">
              <input
                value={chatInput}
                onChange={(event) => setChatInput(event.target.value)}
                onKeyDown={(event) => event.key === "Enter" && handleSend()}
                placeholder="Type your message..."
                className="h-11 w-full rounded-[8px] border border-[#183657] bg-[#0b1c32] px-4 pr-12 text-[12px] text-white outline-none placeholder:text-[#8290a3]"
              />
              <button onClick={handleSend} className="absolute right-1.5 top-1.5 flex h-8 w-8 items-center justify-center rounded-[6px] bg-[#0757e6] text-white">
                <Send className="h-4 w-4" />
              </button>
            </div>
          </section>

          {/* <section className={`${panelClass} dashboard-secondary p-5`}>
            <div className="flex items-start justify-between">
              <div>
                <div className="mb-2 flex items-center gap-2">
                  <span className="h-2.5 w-2.5 rounded-full bg-[#18d589]" />
                  <h2 className="text-[15px] font-semibold text-white">System Status</h2>
                </div>
                <p className="flex items-center gap-2 text-[13px] font-semibold text-[#dfe9f6]">
                  <CheckCircle2 className="h-4 w-4 text-[#19d58a]" />
                  All systems operational
                </p>
                <p className="mt-1 text-[12px] text-[#8998ab]">Everything is running smoothly.</p>
              </div>
              <div className="flex h-16 w-16 items-center justify-center rounded-full border border-[#0d8f5b] text-[#19d58a]">
                <Check className="h-9 w-9" />
              </div>
            </div>
            <button className="mt-4 text-[13px] font-medium text-[#46a8ff]">View status page -&gt;</button>
          </section> */}
        </aside>
      </div>
    </div>
  );
}
